// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SquadCrm.Modules.RoleManagement.Persistence;

#nullable disable

namespace SquadCrm.Modules.RoleManagement.Persistence.Migrations
{
    [DbContext(typeof(RoleManagementDbContext))]
    [Migration("20260901185812_AddDepartmentPermissions")]
    partial class AddDepartmentPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("role_management")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.PermissionChangeAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangedByHandle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("changed_by_handle");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PermissionCodes")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("permission_codes");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.ToTable("permission_change_audit_event", "role_management");
                });

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.PermissionDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("permission_definition", "role_management");

                    b.HasData(
                        new
                        {
                            Code = "roles.view",
                            Description = "View global roles and their assigned permissions.",
                            Module = "Role Management",
                            Name = "View roles"
                        },
                        new
                        {
                            Code = "roles.manage",
                            Description = "Create, update, activate, deactivate, and configure global roles.",
                            Module = "Role Management",
                            Name = "Manage roles"
                        },
                        new
                        {
                            Code = "users.view",
                            Description = "View staff user profiles and their role assignments.",
                            Module = "Staff Management",
                            Name = "View staff users"
                        },
                        new
                        {
                            Code = "users.manage",
                            Description = "Create, update, activate, deactivate staff users, and assign roles.",
                            Module = "Staff Management",
                            Name = "Manage staff users"
                        },
                        new
                        {
                            Code = "audit.view",
                            Description = "View the audit trail of administrative actions.",
                            Module = "Audit",
                            Name = "View audit records"
                        },
                        new
                        {
                            Code = "departments.view",
                            Description = "View departments and their active state.",
                            Module = "Department Management",
                            Name = "View departments"
                        },
                        new
                        {
                            Code = "departments.manage",
                            Description = "Create, update, activate and deactivate departments.",
                            Module = "Department Management",
                            Name = "Manage departments"
                        });
                });

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_code");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCode")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("role", "role_management");
                });

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.RoleAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangedByHandle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("changed_by_handle");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.ToTable("role_audit_event", "role_management");
                });

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("role_permission", "role_management");
                });

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.StaffRoleAssignmentAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangedByHandle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("changed_by_handle");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("RoleCodes")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("role_codes");

                    b.Property<Guid>("StaffSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_subject_id");

                    b.HasKey("Id");

                    b.ToTable("staff_role_assignment_audit_event", "role_management");
                });

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.StaffSubjectRole", b =>
                {
                    b.Property<Guid>("StaffSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_subject_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("StaffSubjectId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("staff_subject_role", "role_management");
                });

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.RolePermission", b =>
                {
                    b.HasOne("SquadCrm.Modules.RoleManagement.Persistence.PermissionDefinition", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SquadCrm.Modules.RoleManagement.Persistence.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SquadCrm.Modules.RoleManagement.Persistence.StaffSubjectRole", b =>
                {
                    b.HasOne("SquadCrm.Modules.RoleManagement.Persistence.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
