// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SquadCrm.Modules.ArchitectureFixture.Persistence;

#nullable disable

namespace SquadCrm.Modules.ArchitectureFixture.Persistence.Migrations
{
    [DbContext(typeof(ArchitectureFixtureDbContext))]
    [Migration("20260826165421_InitialArchitectureFixturePersistence")]
    partial class InitialArchitectureFixturePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("architecture_fixture")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SquadCrm.Modules.ArchitectureFixture.Persistence.PersistenceProbe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at_utc");

                    b.HasKey("Id");

                    b.ToTable("persistence_probe", "architecture_fixture");
                });
#pragma warning restore 612, 618
        }
    }
}
