<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SquadCrm.Modules.StaffIdentity.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/SquadCrm.BuildingBlocks.Abstractions/SquadCrm.BuildingBlocks.Abstractions.csproj" />
  </ItemGroup>
</Project>
